name: SA-2 | Makefile-GO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flow:
    name: Running tests for Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go: [1.16, 1.17]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: make
    - name: Test
      run: make test
